// 3-language support: en / hi / hinglish
export const strings = {
  en: {
    appName: "Ride Media",
    tagline: "Turn Every Ride Into Media",
    selectLang: "Choose Language",
    continue: "Continue",
    onboard: "Onboard — 5 min",
    phone: "Phone (OTP)",
    phonePh: "99999 99999",
    upi: "UPI ID (for payout)",
    upiPh: "name@upi",
    size: "T-Shirt Size",
    zone: "Zone (Pincode)",
    submit: "Submit — Send KYC",
    homeTitle: "Today",
    startEarning: "Start Earning",
    stopEarning: "Stop",
    earningOn: "Earning ON",
    earningOff: "Earning OFF",
    rawKm: "Raw KM",
    ekm: "eKM (Effective)",
    earnings: "Earnings",
    nextCheck: "Next selfie check when bike is stopped (45s)",
    ledger: "Ledger — History",
    mapReplay: "Map Replay",
    wallet: "Wallet",
    balance: "Balance",
    payout: "Payout",
    helmet: "Wear helmet, ride safe. No pay for speeding.",
    pauseInfo: "You get 4 pause days per campaign for sickness.",
  },
  hi: {
    appName: "राइड मीडिया",
    tagline: "हर राइड को मीडिया बनाओ",
    selectLang: "भाषा चुनें",
    continue: "आगे बढ़ें",
    onboard: "ऑनबोर्ड — 5 मिनट",
    phone: "फोन (OTP)",
    phonePh: "99999 99999",
    upi: "UPI ID (पैसे के लिए)",
    upiPh: "name@upi",
    size: "टी-शर्ट साइज",
    zone: "ज़ोन (पिनकोड)",
    submit: "जमा करें — KYC भेजें",
    homeTitle: "आज",
    startEarning: "कमाना शुरू करो",
    stopEarning: "रोकें",
    earningOn: "कमाई चालू",
    earningOff: "कमाई बंद",
    rawKm: "कुल KM",
    ekm: "eKM",
    earnings: "कमाई",
    nextCheck: "अगला सेल्फी चेक जब गाड़ी 45 सेकंड रुकेगी",
    ledger: "हिसाब — लेजर",
    mapReplay: "मैप देखें",
    wallet: "वॉलेट",
    balance: "बैलेंस",
    payout: "पेआउट",
    helmet: "हेलमेट पहनो, सुरक्षित चलो। तेज़ चलाने का पैसा नहीं।",
    pauseInfo: "हर कैंपेन में 4 दिन की छुट्टी मिलेगी।",
  },
  hinglish: {
    appName: "Ride Media",
    tagline: "Har Ride Ko Media Banao",
    selectLang: "Language Chuniye",
    continue: "Continue Karo",
    onboard: "Onboard — 5 min me",
    phone: "Phone (OTP)",
    phonePh: "99999 99999",
    upi: "UPI ID (payout ke liye)",
    upiPh: "name@upi",
    size: "T-Shirt Size",
    zone: "Zone (Pincode)",
    submit: "Submit — KYC bhejo",
    homeTitle: "Aaj Ka",
    startEarning: "Start Earning — Kamao Shuru Karo",
    stopEarning: "Stop — Band Karo",
    earningOn: "Earning ON — Kamaai chal rahi",
    earningOff: "Earning OFF",
    rawKm: "Raw KM",
    ekm: "eKM (Effective)",
    earnings: "Kamaai",
    nextCheck: "Agle selfie check ka time — jab gadi 45 sec ruki ho",
    ledger: "Hisab — Ledger",
    mapReplay: "Map Replay Dekho",
    wallet: "Wallet",
    balance: "Balance",
    payout: "Payout",
    helmet: "Helmet pehno, safe chalo. Speed ka paisa nahi milta.",
    pauseInfo: "4 din pause milenge — bimar ho to use karo",
  }
};

// Simple hook to get current lang from storage
import { useEffect, useState } from 'react';
import * as SecureStore from 'expo-secure-store';
export function useLang() {
  const [lang, setLang] = useState('hinglish');
  useEffect(()=>{ SecureStore.getItemAsync('rm_lang').then(v=>{ if(v) setLang(v); }); },[]);
  const save = async (l) => { setLang(l); await SecureStore.setItemAsync('rm_lang', l); };
  return [lang, save, strings[lang]];
}
